env: "local"
storage_path: "postgres://admin:prRB8xAy6HmwDcusUFHC@localhost:5439/rasp_db?sslmode=disable"
http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
  shutdown_timeout: 15s